### ISSUE TITLE
Add support for the group element in C4 DSL

### ISSUE THREAD

**Issue by geirive** [Midnighter/structurizr-python#72]
### Checklist

- [x] There are [no similar issues or pull requests](https://github.com/Midnighter/structurizr-python/issues) for this yet.

### Is your feature related to a problem? Please describe it.

I want to model an architecture with several different stakeholders in a partnership, and wanted to group components provided from/developed by each partner.

## Describe the solution you would like.

An implementation of the group elemement (see [dsl language reference](https://github.com/structurizr/dsl/blob/master/docs/language-reference.md#group))

## Describe alternatives you considered

I can make use of the DSL or maintain "manual" diagrams for the landscape and potentially context level. 

## Additional context

[Example](https://github.com/structurizr/dsl/blob/master/examples/groups.dsl) can be rendered at https://structurizr.com/dsl demo site.

**Comment by Midnighter** [comment]
Hi @geirive,

Thank you for reporting this missing feature. As far as I know, this is a very recent feature of structurizr. So I think we would first work more basic missing features. Unless you are able to work on this yourself? I'd be happy to discuss how to approach this and review any code submissions.

**Comment by geirive** [comment]
No problem 👍. Yes it is a recent feature, and I fully understand your position.

**Comment by yt-ms** [comment]
This is actually a very useful feature for any diagram that is starting to get complicated.  I had a quick look, and there's an example in DSL [here](https://github.com/structurizr/dsl/blob/master/examples/groups.dsl).  In the JSON (looking at the [Swagger](https://editor.swagger.io/?url=https://raw.githubusercontent.com/structurizr/json/master/structurizr.yaml), this turns into a property on each element rather than being an element in the static model itself.  In the Java implementation, Simon introduced a new [GroupableElement](https://github.com/structurizr/java/blob/master/structurizr-core/src/com/structurizr/model/GroupableElement.java) into the static element type hierarchy which brings this property in, so we probably want to mimic that.

**Comment by yt-ms** [comment]
This is merged to main now.
